language: node_js
node_js:
- 8.9.4
services:
- mongodb
deploy:
  app: vkudla-portfolio
  provider: heroku
  api_key:
    secure: USYibvfaWEKN0UYW9TfNIt6gwFrWDOFWH1R7iMLUnJjq3Cv9MpIaouV2z+VscxsX59PliLFJMkk7vzw0xjghrSpjkexQqpFw/15iC4j3/KMnzgSid0unkaYC2I4tWCtuj/T+e/ODzv3Cke0UJW/3F53uIHAXPs84GpBYwar4Eg59A/vqFenp27wNSBtuViQZ5R2tKNgOmEashpBJ5WsgFu5K457QO6B5oW2/VmfG705lvhlvZ6OwC8+xOeonW1CGhNDHrX+1gKsbGSzddjqEa9CJPPzoKJkPmtxWjvEQdn1f7tpyM+vw3DQHoa1HG9iECXlwL1B+mmwq5M/RPgtRc9fx6yVdZXCiIrxD6e9hgYSJcBaQfQ5cFW78r67tawcI3XPHB1ueEs0dHqJFZXgAHltjhmZWywMvocaTnUGDzlzzWII/g/FNGZHdioCVzXftS0y8lPy6DWp8onpdxY23EGAq9zPx1q58T2XA0C/v0wjEqBZrJIl/Lkk9aA9SQaKLk9LpC9Zy4NMKbgB2MrgHwE11UlZaNV4t6V6me+D5IqrkSyp6MnKyk9PT2TFSqRcZSCCCQVTWrzvhhzKgi4FBn7ssv7WKhttQotUweBycHZZY2gAJaZ+axARXei92vc3zBqB0r7df8UvVNutXXO0XQLb9ydx3gH3BBVsrfj38vbY=
